/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BangGiaRouteImport } from './routes/bang-gia'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCompanyRouteImport } from './routes/admin/company'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminPrivatePolicyRouteImport } from './routes/admin/private-policy'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUserIdChangePasswordRouteImport } from './routes/admin/$userId/change-password'
import { Route as AdminUserIdEditRouteImport } from './routes/admin/$userId/edit'
import { Route as AdminUserIdSettingRouteImport } from './routes/admin/$userId/setting'
import { Route as AdminauthSignInRouteImport } from './routes/admin/(auth)/sign-in'
import { Route as AdminauthSignUpRouteImport } from './routes/admin/(auth)/sign-up'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCustomersCreateCustomerRouteImport } from './routes/admin/customers/create-customer'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminCustomersCustomerIdIndexRouteImport } from './routes/admin/customers/$customerId/index'
import { Route as AdminCustomersCustomerIdEditRouteImport } from './routes/admin/customers/$customerId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BangGiaRoute = BangGiaRouteImport.update({
  id: '/bang-gia',
  path: '/bang-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCompanyRoute = AdminCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPrivatePolicyRoute = AdminPrivatePolicyRouteImport.update({
  id: '/private-policy',
  path: '/private-policy',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserIdChangePasswordRoute =
  AdminUserIdChangePasswordRouteImport.update({
    id: '/$userId/change-password',
    path: '/$userId/change-password',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUserIdEditRoute = AdminUserIdEditRouteImport.update({
  id: '/$userId/edit',
  path: '/$userId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserIdSettingRoute = AdminUserIdSettingRouteImport.update({
  id: '/$userId/setting',
  path: '/$userId/setting',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminauthSignInRoute = AdminauthSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminauthSignUpRoute = AdminauthSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersCreateCustomerRoute =
  AdminCustomersCreateCustomerRouteImport.update({
    id: '/customers/create-customer',
    path: '/customers/create-customer',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersCustomerIdIndexRoute =
  AdminCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCustomersCustomerIdEditRoute =
  AdminCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bang-gia': typeof BangGiaRoute
  '/lien-he': typeof LienHeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/private-policy': typeof AdminPrivatePolicyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$userId/change-password': typeof AdminUserIdChangePasswordRoute
  '/admin/$userId/edit': typeof AdminUserIdEditRoute
  '/admin/$userId/setting': typeof AdminUserIdSettingRoute
  '/admin/sign-in': typeof AdminauthSignInRoute
  '/admin/sign-up': typeof AdminauthSignUpRoute
  '/admin/customers/create-customer': typeof AdminCustomersCreateCustomerRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/customers/$customerId/': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bang-gia': typeof BangGiaRoute
  '/lien-he': typeof LienHeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/private-policy': typeof AdminPrivatePolicyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$userId/change-password': typeof AdminUserIdChangePasswordRoute
  '/admin/$userId/edit': typeof AdminUserIdEditRoute
  '/admin/$userId/setting': typeof AdminUserIdSettingRoute
  '/admin/sign-in': typeof AdminauthSignInRoute
  '/admin/sign-up': typeof AdminauthSignUpRoute
  '/admin/customers/create-customer': typeof AdminCustomersCreateCustomerRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bang-gia': typeof BangGiaRoute
  '/lien-he': typeof LienHeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/company': typeof AdminCompanyRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/private-policy': typeof AdminPrivatePolicyRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$userId/change-password': typeof AdminUserIdChangePasswordRoute
  '/admin/$userId/edit': typeof AdminUserIdEditRoute
  '/admin/$userId/setting': typeof AdminUserIdSettingRoute
  '/admin/(auth)/sign-in': typeof AdminauthSignInRoute
  '/admin/(auth)/sign-up': typeof AdminauthSignUpRoute
  '/admin/customers/create-customer': typeof AdminCustomersCreateCustomerRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/customers/$customerId/edit': typeof AdminCustomersCustomerIdEditRoute
  '/admin/customers/$customerId/': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bang-gia'
    | '/lien-he'
    | '/admin/analytics'
    | '/admin/company'
    | '/admin/employees'
    | '/admin/private-policy'
    | '/admin/settings'
    | '/admin/'
    | '/admin/$userId/change-password'
    | '/admin/$userId/edit'
    | '/admin/$userId/setting'
    | '/admin/sign-in'
    | '/admin/sign-up'
    | '/admin/customers/create-customer'
    | '/admin/customers/'
    | '/admin/projects/'
    | '/admin/customers/$customerId/edit'
    | '/admin/customers/$customerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bang-gia'
    | '/lien-he'
    | '/admin/analytics'
    | '/admin/company'
    | '/admin/employees'
    | '/admin/private-policy'
    | '/admin/settings'
    | '/admin'
    | '/admin/$userId/change-password'
    | '/admin/$userId/edit'
    | '/admin/$userId/setting'
    | '/admin/sign-in'
    | '/admin/sign-up'
    | '/admin/customers/create-customer'
    | '/admin/customers'
    | '/admin/projects'
    | '/admin/customers/$customerId/edit'
    | '/admin/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bang-gia'
    | '/lien-he'
    | '/admin/analytics'
    | '/admin/company'
    | '/admin/employees'
    | '/admin/private-policy'
    | '/admin/settings'
    | '/admin/'
    | '/admin/$userId/change-password'
    | '/admin/$userId/edit'
    | '/admin/$userId/setting'
    | '/admin/(auth)/sign-in'
    | '/admin/(auth)/sign-up'
    | '/admin/customers/create-customer'
    | '/admin/customers/'
    | '/admin/projects/'
    | '/admin/customers/$customerId/edit'
    | '/admin/customers/$customerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BangGiaRoute: typeof BangGiaRoute
  LienHeRoute: typeof LienHeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-gia': {
      id: '/bang-gia'
      path: '/bang-gia'
      fullPath: '/bang-gia'
      preLoaderRoute: typeof BangGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/company': {
      id: '/admin/company'
      path: '/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AdminCompanyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/private-policy': {
      id: '/admin/private-policy'
      path: '/private-policy'
      fullPath: '/admin/private-policy'
      preLoaderRoute: typeof AdminPrivatePolicyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$userId/change-password': {
      id: '/admin/$userId/change-password'
      path: '/$userId/change-password'
      fullPath: '/admin/$userId/change-password'
      preLoaderRoute: typeof AdminUserIdChangePasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$userId/edit': {
      id: '/admin/$userId/edit'
      path: '/$userId/edit'
      fullPath: '/admin/$userId/edit'
      preLoaderRoute: typeof AdminUserIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$userId/setting': {
      id: '/admin/$userId/setting'
      path: '/$userId/setting'
      fullPath: '/admin/$userId/setting'
      preLoaderRoute: typeof AdminUserIdSettingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/(auth)/sign-in': {
      id: '/admin/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminauthSignInRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/(auth)/sign-up': {
      id: '/admin/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/admin/sign-up'
      preLoaderRoute: typeof AdminauthSignUpRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/create-customer': {
      id: '/admin/customers/create-customer'
      path: '/customers/create-customer'
      fullPath: '/admin/customers/create-customer'
      preLoaderRoute: typeof AdminCustomersCreateCustomerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/$customerId/': {
      id: '/admin/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId/'
      preLoaderRoute: typeof AdminCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers/$customerId/edit': {
      id: '/admin/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/admin/customers/$customerId/edit'
      preLoaderRoute: typeof AdminCustomersCustomerIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCompanyRoute: typeof AdminCompanyRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminPrivatePolicyRoute: typeof AdminPrivatePolicyRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUserIdChangePasswordRoute: typeof AdminUserIdChangePasswordRoute
  AdminUserIdEditRoute: typeof AdminUserIdEditRoute
  AdminUserIdSettingRoute: typeof AdminUserIdSettingRoute
  AdminauthSignInRoute: typeof AdminauthSignInRoute
  AdminauthSignUpRoute: typeof AdminauthSignUpRoute
  AdminCustomersCreateCustomerRoute: typeof AdminCustomersCreateCustomerRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminCustomersCustomerIdEditRoute: typeof AdminCustomersCustomerIdEditRoute
  AdminCustomersCustomerIdIndexRoute: typeof AdminCustomersCustomerIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCompanyRoute: AdminCompanyRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminPrivatePolicyRoute: AdminPrivatePolicyRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUserIdChangePasswordRoute: AdminUserIdChangePasswordRoute,
  AdminUserIdEditRoute: AdminUserIdEditRoute,
  AdminUserIdSettingRoute: AdminUserIdSettingRoute,
  AdminauthSignInRoute: AdminauthSignInRoute,
  AdminauthSignUpRoute: AdminauthSignUpRoute,
  AdminCustomersCreateCustomerRoute: AdminCustomersCreateCustomerRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminCustomersCustomerIdEditRoute: AdminCustomersCustomerIdEditRoute,
  AdminCustomersCustomerIdIndexRoute: AdminCustomersCustomerIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BangGiaRoute: BangGiaRoute,
  LienHeRoute: LienHeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
