/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BangGiaRouteImport } from './routes/bang-gia'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as AuthResetRouteImport } from './routes/_auth/reset'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUserIdIndexRouteImport } from './routes/admin/$userId/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin/projects/$projectId'
import { Route as AdminProjectsNewRouteImport } from './routes/admin/projects/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BangGiaRoute = BangGiaRouteImport.update({
  id: '/bang-gia',
  path: '/bang-gia',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/_auth/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserIdIndexRoute = AdminUserIdIndexRouteImport.update({
  id: '/$userId/',
  path: '/$userId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bang-gia': typeof BangGiaRoute
  '/lien-he': typeof LienHeRoute
  '/reset': typeof AuthResetRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/$userId/': typeof AdminUserIdIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bang-gia': typeof BangGiaRoute
  '/lien-he': typeof LienHeRoute
  '/reset': typeof AuthResetRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/$userId': typeof AdminUserIdIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bang-gia': typeof BangGiaRoute
  '/lien-he': typeof LienHeRoute
  '/_auth/reset': typeof AuthResetRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/$userId/': typeof AdminUserIdIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bang-gia'
    | '/lien-he'
    | '/reset'
    | '/sign-in'
    | '/sign-up'
    | '/admin/settings'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/$userId/'
    | '/admin/posts/'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bang-gia'
    | '/lien-he'
    | '/reset'
    | '/sign-in'
    | '/sign-up'
    | '/admin/settings'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/$userId'
    | '/admin/posts'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bang-gia'
    | '/lien-he'
    | '/_auth/reset'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/admin/settings'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/$userId/'
    | '/admin/posts/'
    | '/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BangGiaRoute: typeof BangGiaRoute
  LienHeRoute: typeof LienHeRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-gia': {
      id: '/bang-gia'
      path: '/bang-gia'
      fullPath: '/bang-gia'
      preLoaderRoute: typeof BangGiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset': {
      id: '/_auth/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$userId/': {
      id: '/admin/$userId/'
      path: '/$userId'
      fullPath: '/admin/$userId/'
      preLoaderRoute: typeof AdminUserIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminUserIdIndexRoute: typeof AdminUserIdIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminUserIdIndexRoute: AdminUserIdIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BangGiaRoute: BangGiaRoute,
  LienHeRoute: LienHeRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
